export const FALLBACK = [
  { id: 1,  name: '따뜻한 아메리카노', category: '커피',      price: 4500, description: '진하고 고소한 풍미의 대표 커피',                       img: '/menu/01_americano.png',         hasTemp: true  },
  { id: 2,  name: '카페라떼',          category: '커피',      price: 5000, description: '부드러운 우유와 진한 에스프레소가 어우러진 고소한 커피', img: '/menu/02_cafe_latte.png',        hasTemp: true  },
  { id: 3,  name: '바닐라 라떼',       category: '커피',      price: 5500, description: '달콤하고 부드러운 바닐라 시럽이 어우러진 라떼',          img: '/menu/03_vanilla_latte.png',     hasTemp: true  },
  { id: 4,  name: '카라멜 마키아토',   category: '커피',      price: 5500, description: '달콤한 카라멜 시럽과 에스프레소의 환상적인 조화',        img: '/menu/04_caramel_macchiato.png', hasTemp: true  },
  { id: 5,  name: '카푸치노',          category: '커피',      price: 5000, description: '풍성한 우유 거품과 에스프레소의 클래식한 커피',          img: '/menu/05_cappuccino.png',        hasTemp: true  },
  { id: 6,  name: '헤이즐넛 라떼',     category: '커피',      price: 5500, description: '고소한 헤이즐넛 향이 가득한 부드러운 라떼',             img: '/menu/06_hazelnut_latte.png',    hasTemp: true  },
  { id: 7,  name: '아이스 콜드브루',   category: '커피',      price: 4500, description: '장시간 저온 추출로 완성한 깔끔하고 부드러운 커피',       img: '/menu/07_cold_brew.png',         hasTemp: false },
  { id: 8,  name: '아인슈페너',        category: '커피',      price: 5500, description: '진한 에스프레소 위에 달콤한 생크림을 얹은 비엔나 커피',  img: '/menu/08_einspanner.png',        hasTemp: false },
  { id: 9,  name: '초코 라떼',         category: '논커피',    price: 5500, description: '진한 초코소스와 부드러운 우유가 어우러진 달콤한 음료',   img: '/menu/09_choco_latte.png',       hasTemp: true  },
  { id: 10, name: '녹차 라떼',         category: '논커피',    price: 5500, description: '고소한 녹차와 부드러운 우유가 조화로운 음료',            img: '/menu/10_greentea_latte.png',    hasTemp: true  },
  { id: 11, name: '딸기 라떼',         category: '논커피',    price: 6000, description: '상큼한 딸기와 부드러운 우유가 어우러진 달콤한 라떼',     img: '/menu/11_strawberry_latte.png',  hasTemp: true  },
  { id: 12, name: '고구마 라떼',       category: '논커피',    price: 5500, description: '달콤하고 고소한 고구마의 풍미가 가득한 라떼',            img: '/menu/12_sweetpotato_latte.png', hasTemp: true  },
  { id: 13, name: '자몽 에이드',       category: '티/에이드', price: 6000, description: '상큼한 자몽과 탄산이 만나 청량감 넘치는 에이드',         img: '/menu/13_grapefruit_ade.png',    hasTemp: false },
  { id: 14, name: '레몬 에이드',       category: '티/에이드', price: 6000, description: '레몬의 상큼함과 탄산의 상쾌함이 만난 활력 에이드',       img: '/menu/14_lemon_ade.png',         hasTemp: false },
  { id: 15, name: '청포도 에이드',     category: '티/에이드', price: 6000, description: '청포도의 달콤하고 시원한 맛이 가득한 에이드',            img: '/menu/15_greengrape_ade.png',    hasTemp: false },
  { id: 16, name: '캐모마일 티',       category: '티/에이드', price: 5000, description: '마음이 편안해지는 향긋한 허브티',                       img: '/menu/16_chamomile_tea.png',     hasTemp: true  },
  { id: 17, name: '치즈 케이크',       category: '디저트',    price: 7500, description: '진한 치즈의 맛을 달콤하고 부드럽게 느낄 수 있는 케이크', img: '/menu/17_cheesecake.png',        hasTemp: false },
  { id: 18, name: '크로플',            category: '디저트',    price: 6000, description: '크루아상과 와플을 결합한 바삭하고 달콤한 디저트',         img: '/menu/18_croffle.png',           hasTemp: false },
  { id: 19, name: '초코 머핀',         category: '디저트',    price: 4000, description: '촉촉하고 진한 초콜릿 풍미의 부드러운 머핀',              img: '/menu/19_choco_muffin.png',      hasTemp: false },
  { id: 20, name: '마카롱 세트 (3개)', category: '디저트',    price: 4500, description: '겉은 바삭하고 속은 쫀득한 달콤한 마카롱 3종 세트',       img: '/menu/20_macaron_set.png',       hasTemp: false },
]
